name: Weather Alert Bot

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  weather-alert:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python weather_alert.py